export const Terms = {
  content:
    'LoreNulla ea reprehenderit ipsum commodo. Mollit officia proident non qui sint ex deserunt culpa irure. Deserunt consectetur pariatur elit ut veniam. Reprehenderit aliqua ea amet reprehenderit labore dolore ea Lorem sint irure. Amet minim eu mollit mollit ex voluptate dolore velit.\
                    Cupidatat voluptate velit reprehenderit consequat veniam anim nostrud pariatur cupidatat Lorem pariatur incididunt commodo. Aliquip sit amet occaecat commodo Lorem ut reprehenderit excepteur aliqua. Eu et pariatur aliqua ut velit aliquip adipisicing officia exercitation. Exercitation cillum ut labore non anim. Mollit aute elit commodo quis sint. Nulla officia fugiat est sunt laboris do eiusmod aute nostrud dolor. Cupidatat tempor sit est sunt in est laborum sit.\
                    Tempor cillum laboris nulla culpa et consequat id tempor non. Elit nostrud fugiat ut Lorem dolore amet esse ex nulla pariatur cupidatat mollit sunt. Et pariatur adipisicing irure non culpa. Aute occaecat velit officia reprehenderit quis ex dolore. Commodo in laboris occaecat minim veniam sunt ad dolor id esse reprehenderit minim cupidatat irure. Do labore magna dolore nisi.',
};

export const Privacy = {
  content:
    'Sunt magna eu cupidatat ad proident tempor culpa. Et in quis laboris commodo amet sunt laborum. Velit cillum sint cillum deserunt reprehenderit tempor fugiat laboris id. Sunt sit consequat ad voluptate dolore amet ipsum exercitation do velit. Aute commodo officia adipisicing id esse deserunt laborum consectetur cillum aliquip nostrud culpa ut.\
        Amet cillum tempor in laborum. Laborum ea ea magna reprehenderit. Nisi quis sint occaecat aute aliquip Lorem reprehenderit in esse veniam ea voluptate enim quis. Incididunt ipsum consectetur non elit officia laboris nulla sit nostrud nostrud id excepteur. Adipisicing cupidatat sunt tempor quis adipisicing et aliqua do sint ex magna aliqua. Duis ut cupidatat do elit adipisicing aliquip. Enim incididunt veniam eiusmod dolor nisi est ipsum nisi.\
        Ad incididunt duis cupidatat occaecat ex eu. Enim dolor proident in ullamco sint mollit nulla enim nisi anim duis est nostrud sunt. Ullamco duis do labore labore ipsum aliqua non occaecat magna elit. Deserunt aute aliquip occaecat cupidatat sunt sit fugiat aute consequat velit deserunt dolor. Reprehenderit eu reprehenderit amet sit sunt commodo in exercitation. Consectetur non deserunt officia aliqua. Quis eiusmod occaecat proident tempor dolor culpa qui tempor.\
        Cillum non enim mollit et amet. Ex do et sit enim excepteur ullamco eu reprehenderit culpa quis eiusmod dolor fugiat. Proident laborum elit laborum qui irure consequat ipsum commodo consectetur commodo. Ut velit veniam eu id aliqua incididunt eu fugiat enim mollit veniam eiusmod velit. Duis officia ipsum aliquip sit non cillum.\
        Incididunt et non magna adipisicing commodo cupidatat laboris veniam in enim voluptate. Est Lorem consectetur esse deserunt nisi magna ex. Ad nostrud Lorem in anim eu velit anim nulla eiusmod magna irure culpa ad aliqua.\
        Reprehenderit et duis dolor fugiat ullamco dolor fugiat. Velit pariatur mollit commodo cupidatat velit qui eiusmod ad ullamco. Voluptate aliqua commodo est labore eiusmod aliqua aliqua reprehenderit eiusmod consectetur mollit qui aliqua in. Enim dolor tempor proident magna consectetur tempor ad exercitation sunt sint. In irure dolore consequat consectetur aute dolor consectetur et.',
};
