export const GET_FLIGHTS_REQUESTED = "GET_FLIGHTS_REQUESTED";
export const GET_FLIGHTS_SUCCESS = "GET_FLIGHTS_SUCCESS";
export const GET_FLIGHTS_FAILED = "GET_FLIGHTS_FAILED";

export const ADD_FLIGHTS_REQUESTED = "ADD_FLIGHTS_REQUESTED";
export const ADD_FLIGHTS_SUCCESS = "ADD_FLIGHTS_SUCCESS";
export const ADD_FLIGHTS_FAILED = "ADD_FLIGHTS_FAILED";

export const GET_FLIGHTSDETAILSBYID_REQUESTED = "GET_FLIGHTSDETAILSBYID_REQUESTED";
export const GET_FLIGHTSDETAILSBYID_SUCCESS = "GET_FLIGHTSDETAILSBYID_SUCCESS";
export const GET_FLIGHTSDETAILSBYID_FAILED = "GET_FLIGHTSDETAILSBYID_FAILED";

export const UPDATE_FLIGHTS_REQUESTED = "UPDATE_FLIGHTS_REQUESTED";
export const UPDATE_FLIGHTS_SUCCESS = "UPDATE_FLIGHTS_SUCCESS";
export const UPDATE_FLIGHTS_FAILED = "UPDATE_FLIGHTS_FAILED";

export const DELETE_FLIGHTS_REQUESTED = "DELETE_FLIGHTS_REQUESTED";
export const DELETE_FLIGHTS_SUCCESS = "DELETE_FLIGHTS_SUCCESS";
export const DELETE_FLIGHTS_FAILED = "DELETE_FLIGHTS_FAILED";

export const GET_HOTELS_REQUESTED = "GET_HOTELS_REQUESTED";
export const GET_HOTELS_SUCCESS = "GET_HOTELS_SUCCESS";
export const GET_HOTELS_FAILED = "GET_HOTELS_FAILED";

export const ADD_HOTEL_REQUESTED = "ADD_HOTEL_REQUESTED";
export const ADD_HOTEL_SUCCESS = "ADD_HOTEL_SUCCESS";
export const ADD_HOTEL_FAILED = "ADD_HOTEL_FAILED";

export const GET_HOTELDETAILSBYID_REQUESTED = "GET_HOTELDETAILSBYID_REQUESTED";
export const GET_HOTELDETAILSBYID_SUCCESS = "GET_HOTELDETAILSBYID_SUCCESS";
export const GET_HOTELDETAILSBYID_FAILED = "GET_HOTELDETAILSBYID_FAILED";

export const UPDATE_HOTEL_REQUESTED = "UPDATE_HOTEL_REQUESTED";
export const UPDATE_HOTEL_SUCCESS = "UPDATE_HOTEL_SUCCESS";
export const UPDATE_HOTEL_FAILED = "UPDATE_HOTEL_FAILED";

export const DELETE_HOTEL_REQUESTED = "DELETE_HOTEL_REQUESTED";
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS";
export const DELETE_HOTEL_FAILED = "DELETE_HOTEL_FAILED";

export const SEARCH_HOTEL_DETAILS_REQUESTED = "SEARCH_HOTEL_DETAILS_REQUESTED";
export const SEARCH_HOTEL_DETAILS_SUCCESS = "SEARCH_HOTEL_DETAILS_SUCCESS";
export const SEARCH_HOTEL_DETAILS_FAILED = "SEARCH_HOTEL_DETAILS_FAILED";

export const GET_TRIPS_REQUESTED = "GET_TRIPS_REQUESTED";
export const GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS";
export const GET_TRIPS_FAILED = "GET_TRIPS_FAILED";

export const SEARCH_TRIP_DETAILS_REQUESTED = "SEARCH_TRIP_DETAILS_REQUESTED";
export const SEARCH_TRIP_DETAILS_SUCCESS = "SEARCH_TRIP_DETAILS_SUCCESS";
export const SEARCH_TRIP_DETAILS_FAILED = "SEARCH_TRIP_DETAILS_FAILED";

export const FILTER_TRIP_DETAILS_REQUESTED = "FILTER_TRIP_DETAILS_REQUESTED";
export const FILTER_TRIP_DETAILS_SUCCESS = "FILTER_TRIP_DETAILS_SUCCESS";
export const FILTER_DETAILS_FAILED = "FILTER_TRIP_DETAILS_FAILED";

export const GET_TRIP_DETAILSBYID_REQUESTED = "GET_TRIP_DETAILSBYID_REQUESTED";
export const GET_TRIP_DETAILSBYID_SUCCESS = "GET_TRIP_DETAILSBYID_SUCCESS";
export const GET_TRIP_DETAILSBYID_FAILED = "GET_TRIP_DETAILSBYID_FAILED";

export const GET_SINGIN_REQUESTED = "GET_SINGIN_REQUESTED";
export const GET_SINGIN_SUCCESS = "GET_SINGIN_SUCCESS";
export const GET_SINGIN_FAILED = "GET_SINGIN_FAILED";

export const UPDATE_TRIPS_REQUESTED = "UPDATE_TRIPS_REQUESTED";
export const UPDATE_TRIPS_REQUESTED_FULFILL = "UPDATE_TRIPS_REQUESTED_FULFILL";
export const UPDATE_TRIPS_SUCCESS = "UPDATE_TRIPS_SUCCESS";
export const UPDATE_TRIPS_FAILED = "UPDATE_TRIPS_FAILED";

export const ADD_TRIPS_REQUESTED = "ADD_TRIPS_REQUESTED";
export const ADD_TRIPS_SUCCESS = "ADD_TRIPS_SUCCESS";
export const ADD_TRIPS_FAILED = "ADD_TRIPS_FAILED";

export const DELETE_TRIPS_REQUESTED = "DELETE_TRIPS_REQUESTED";
export const DELETE_TRIPS_SUCCESS = "DELETE_TRIPS_SUCCESS";
export const DELETE_TRIPS_FAILED = "DELETE_TRIPS_FAILED";

export const GET_DROPS_REQUESTED = "GET_DROPS_REQUESTED";
export const GET_DROPS_SUCCESS = "GET_DROPS_SUCCESS";
export const GET_DROPS_FAILED = "GET_DROPS_FAILED";

export const ADD_DROPS_REQUESTED = "ADD_DROPS_REQUESTED";
export const ADD_DROPS_SUCCESS = "ADD_DROPS_SUCCESS";
export const ADD_DROPS_FAILED = "ADD_DROPS_FAILED";

export const DELETE_DROPDETAILS_REQUESTED = "DELETE_DROPDETAILS_REQUESTED";
export const DELETE_DROPDETAILS_SUCCESS = "DELETE_DROPDETAILS_SUCCESS";
export const DELETE_DROPDETAILS_FAILED = "DELETE_DROPDETAILS_FAILED";

export const UPDATE_DROPDETAILS_REQUESTED = "UPDATE_DROPDETAILS_REQUESTED";
export const UPDATE_DROPDETAILS_SUCCESS = "UPDATE_DROPDETAILS_SUCCESS";
export const UPDATE_DROPDETAILS_FAILED = "UPDATE_DROPDETAILS_FAILED";

export const GET_CUSTOMERS_REQUESTED = "GET_CUSTOMERS_REQUESTED";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_FAILED = "GET_CUSTOMERS_FAILED";

export const SEARCH_CUSTOMER_DETAILS_REQUESTED = "SEARCH_CUSTOMER_DETAILS_REQUESTED";
export const SEARCH_CUSTOMER_DETAILS_SUCCESS = "SEARCH_CUSTOMER_DETAILS_SUCCESS";
export const SEARCH_CUSTOMER_DETAILS_FAILED = "SEARCH_CUSTOMER_DETAILS_FAILED";

export const GET_CUSTOMERSDETAILSBYID_REQUESTED = "GET_CUSTOMERSDETAILSBYID_REQUESTED";
export const GET_CUSTOMERSDETAILSBYID_SUCCESS = "GET_CUSTOMERSDETAILSBYID_SUCCESS";
export const GET_CUSTOMERSDETAILSBYID_FAILED = "GET_CUSTOMERSDETAILSBYID_FAILED";

export const UPDATE_CUSTOMERSDETAILS_REQUESTED = "UPDATE_CUSTOMERSDETAILS_REQUESTED";
export const UPDATE_CUSTOMERSDETAILS_SUCCESS = "UPDATE_CUSTOMERSDETAILS_SUCCESS";
export const UPDATE_CUSTOMERSDETAILS_FAILED = "UPDATE_CUSTOMERSDETAILS_FAILED";

export const DELETE_CUSTOMERSDETAILS_REQUESTED = "DELETE_CUSTOMERSDETAILS_REQUESTED";
export const DELETE_CUSTOMERSDETAILS_SUCCESS = "DELETE_CUSTOMERSDETAILS_SUCCESS";
export const DELETE_CUSTOMERSDETAILS_FAILED = "DELETE_CUSTOMERSDETAILS_FAILED";

export const SIGN_OUT_REQUESTED = "SIGN_OUT_REQUESTED";
export const SET_TOKEN ="SET_TOKEN";

 export const RESET_PASSWORD_REQUESTED = "RESET_PASSWORD_REQUESTED";
 export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
 export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
